// Local backend: discover and parse `.specstory/history/*.md` files written by
// the SpecStory CLI. Zero config, no API key. Produces the same normalized
// session shape as cloud.mjs so command scripts are backend-agnostic.
//
// Local file format (SpecStory Markdown v2.x):
//   <!-- Generated by SpecStory, Markdown vX.Y.Z -->
//   # 2026-05-26 12:23:21Z
//   <!-- <Tool> Session <uuid> (2026-05-26 12:23:21Z) -->
//   _**User (2026-05-26 12:23:21Z)**_  ...
//   _**Agent (claude-opus-4-7 2026-05-26 12:24:16Z)**_ ...
// Filenames: YYYY-MM-DD_HH-MM-SSZ[-<slug>].md

import fs from "node:fs";
import path from "node:path";
import { expandHome } from "./common.mjs";

const HISTORY_REL = path.join(".specstory", "history");
const PRUNE = new Set(["node_modules", ".git", ".venv", "venv", "dist", "build", ".next", "__pycache__"]);

// Walk up from `start` to the filesystem root, returning the first dir that
// contains `.specstory/history`. Mirrors SpecStory's own single-project skills.
export function findHistoryUpward(start = process.cwd()) {
  let dir = path.resolve(start);
  for (;;) {
    const candidate = path.join(dir, HISTORY_REL);
    if (isDir(candidate)) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

// Find every `.specstory/history` dir under `root` (bounded depth), pruning
// heavy/irrelevant directories. Each match is one project.
export function findHistoryDirs(root, maxDepth = 4) {
  const out = [];
  const base = path.resolve(expandHome(root));
  walk(base, 0);
  return out;

  function walk(dir, depth) {
    if (depth > maxDepth) return;
    const hist = path.join(dir, HISTORY_REL);
    if (isDir(hist)) out.push(hist);
    let entries = [];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (!e.isDirectory() || e.name.startsWith(".") || PRUNE.has(e.name)) continue;
      walk(path.join(dir, e.name), depth + 1);
    }
  }
}

// List local sessions. Resolution:
//   - opts.root  → scan recursively for all projects under root
//   - else       → nearest `.specstory/history` walking up from opts.cwd
export function listLocalSessions({ root = "", cwd = process.cwd(), withContent = false } = {}) {
  const dirs = root ? findHistoryDirs(root) : [findHistoryUpward(cwd)].filter(Boolean);
  const sessions = [];
  for (const dir of dirs) {
    const projectName = projectNameFor(dir);
    let files = [];
    try {
      files = fs.readdirSync(dir).filter((f) => f.endsWith(".md"));
    } catch {
      continue;
    }
    for (const f of files) {
      const full = path.join(dir, f);
      const s = parseLocalFile(full, projectName, withContent);
      if (s) sessions.push(s);
    }
  }
  return sessions;
}

export function localHistoryAvailable({ root = "", cwd = process.cwd() } = {}) {
  if (root) return findHistoryDirs(root).length > 0;
  return findHistoryUpward(cwd) != null;
}

// Read full markdown for a session that was listed without content.
export function readContent(filePath) {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
}

function parseLocalFile(filePath, projectName, withContent) {
  let md;
  try {
    md = fs.readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
  const base = path.basename(filePath, ".md");

  // Filename: YYYY-MM-DD_HH-MM-SSZ[-slug]
  const fnMatch = base.match(/^(\d{4}-\d{2}-\d{2})_(\d{2})-(\d{2})-(\d{2})Z(?:-(.*))?$/);
  const slug = fnMatch?.[5] || "";
  const fileIso = fnMatch
    ? `${fnMatch[1]}T${fnMatch[2]}:${fnMatch[3]}:${fnMatch[4]}Z`
    : null;

  // Session comment: tool + uuid. e.g. "<!-- Claude Code Session <uuid> (ts) -->"
  const sessMatch = md.match(/<!--\s*(.+?)\s+Session\s+([0-9a-fA-F-]{8,})\s*\(([^)]+)\)\s*-->/);
  const tool = sessMatch?.[1]?.trim() || null;
  const sessionId = sessMatch?.[2] || `local:${base}`;

  // All exchange timestamps (User + Agent) → start/end span.
  const tsMarks = [...md.matchAll(/_\*\*(?:User|Agent) \(([^)]*?(\d{4}-\d{2}-\d{2}) (\d{2}:\d{2}:\d{2})Z)\)\*\*_/g)];
  const isoStamps = tsMarks
    .map((m) => `${m[2]}T${m[3]}Z`)
    .filter((s) => !isNaN(new Date(s)));
  const firstIso = isoStamps[0] || fileIso;
  const lastIso = isoStamps.length ? isoStamps[isoStamps.length - 1] : fileIso;

  // Models from Agent markers: "_**Agent (<model> <date> <time>Z)**_"
  const models = new Set();
  for (const m of md.matchAll(/_\*\*Agent \(([^)\s]+)\s+\d{4}-\d{2}-\d{2}/g)) {
    // Skip bare timestamps and synthetic/placeholder model tokens like "<synthetic>".
    if (m[1] && !/^\d/.test(m[1]) && !m[1].startsWith("<")) models.add(m[1]);
  }

  const name = deriveName(slug, md, base);

  return {
    source: "local",
    sessionId,
    projectId: projectName,
    projectName,
    name,
    userTitle: slug ? titleize(slug) : null,
    createdAt: fileIso || firstIso,
    updatedAt: lastIso,
    startedAt: firstIso,
    endedAt: lastIso,
    markdownContent: withContent ? md : null,
    filePath,
    metadata: {
      clientName: tool,
      agentName: tool,
      llmModels: [...models],
      gitBranches: [], // not reliably in the file; recap can extract from content
      tags: [],
      summary: null,
    },
  };
}

function deriveName(slug, md, base) {
  if (slug) return titleize(slug);
  // First real user prompt: scan all user blocks, after removing command/stdout/
  // caveat blocks entirely (sessions often open with /clear, /model and their
  // echoed stdout). Strip ANSI codes too.
  for (const m of md.matchAll(/_\*\*User \([^)]+\)\*\*_\s*\n+([\s\S]*?)(?=\n---|\n_\*\*)/g)) {
    const cleaned = m[1]
      .replace(/<command-name>[\s\S]*?<\/command-name>/g, "")
      .replace(/<command-message>[\s\S]*?<\/command-message>/g, "")
      .replace(/<command-args>[\s\S]*?<\/command-args>/g, "")
      .replace(/<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g, "")
      .replace(/<local-command-caveat>[\s\S]*?<\/local-command-caveat>/g, "")
      .replace(/<[^>]+>/g, " ")
      .replace(/\[[0-9;]*m/g, ""); // ANSI escapes
    const line = cleaned
      .split("\n")
      .map((l) => l.trim())
      .find((l) => l && !l.startsWith("/") && !l.startsWith("Caveat:"));
    if (line) return line.slice(0, 80);
  }
  return base;
}

function titleize(slug) {
  return slug
    .replace(/-/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function projectNameFor(historyDir) {
  // historyDir = <project>/.specstory/history → project basename
  return path.basename(path.dirname(path.dirname(historyDir)));
}

function isDir(p) {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}
